version: '2'
services:
  plex:
    restart: unless-stopped
    privileged: true
    container_name: plex
    image: plexinc/pms-docker
    environment:
      - TZ=US
      - PLEX_CLAIM="${PLEX_CLAIM}"
    network_mode: host
    volumes:
      - "${PLEX_DIRECTORY}/config:/config"
      - "${PLEX_DIRECTORY}/transcode:/transcode"
      - "${PLEX_DIRECTORY}/data:/data"
      - "${NAS_MNT_LOCATION}:${NAS_MNT_LOCATION}"

  sonarr:
    restart: unless-stopped
    privileged: true
    container_name: sonarr
    image: linuxserver/sonarr
    environment:
      - TZ=US
      - PGID=0
      - PUID=0
    ports:
      - "8989:8989"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "${SONARR_DIRECTORY}/config:/config"
      - "${NAS_MNT_LOCATION}/anime:/tv"
      - "${SEEDBOX_DOWNLOAD_MOUNT}:/downloads" # since transmission reports back its download dir and sonarr looks for it locally, that means the download dir of transmission and this docker container need to be the same
      