version: '2'
services:
  plex:
    restart: unless-stopped
    privileged: true
    container_name: plex
    image: plexinc/pms-docker
    environment:
      - TZ=US
      - PLEX_CLAIM="${PLEX_CLAIM}"
    network_mode: host
    volumes:
      - "${PLEX_DIRECTORY}/config:/config"
      - "${PLEX_DIRECTORY}/transcode:/transcode"
      - "${PLEX_DIRECTORY}/data:/data"
      - "${PLEX_MNT_LOCATION}:${PLEX_MNT_LOCATION}"

  sonarr:
    restart: unless-stopped
    privileged: true
    container_name: sonarr
    image: linuxserver/sonarr
    environment:
      - TZ=US
      - PGID=0
      - PUID=0
    ports:
      - "8989:8989"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "${SONARR_DIRECTORY}/config:/config"
      - "${PLEX_MNT_LOCATION}/anime:/tv"
      - "${PLEX_MNT_LOCATION}/sonarr/downloads:/downloads"

  sabnzbd:
    restart: unless-stopped
    container_name: sabnzbd
    image: sabnzbd/sabnzbd
    ports:
      - "8080:8080"
    volumes:
      - "${SABNZBD_DIRECTORY}/datadir:/datadir"
      - "${SABNZBD_DIRECTORY}/media:/media"
