---
- hosts: all
  vars:
    nas_name: HeadlessNAS
    nas_mount_location: /mnt/headlessNAS
    plex_directory: /srv/plex
    sabnzbd_directory: /srv/sabnzbd
    sonarr_directory: /srv/sonarr

    docker_compose_file_location_local: "{{ playbook_dir}}/../docker/docker-compose.yml"

    # The below environment file location is hardcoded in the systemd script
    environment_file_location: "/etc/environment"

    plex_startup_script: plex_server
    plex_startup_script_local_location: "{{ playbook_dir }}/../systemd/{{ plex_startup_script }}"
    # The below script location is hardcoded in the systemd script
    plex_startup_script_bin_location: "/usr/local/bin/{{ plex_startup_script }}"
    
    systemd_file_location_local: "{{ playbook_dir  }}/../systemd/plex_server.service"
    systemd_file_location: "/etc/systemd/system/plex_server.service"

  tasks:
    # include other var files
    - name: include secrets file
      include_vars: secrets.yml
   
    # Install pre-requisite libraries
    - name: install docker
      apt:
        name: docker
        state: present
    - name: install docker-compose
      apt:
        name: docker-compose
        state: present
    - name: install cifs-utils (for mounting NAS)
      apt:
        name: cifs-utils
        state: present
    - name: install avahi (gives ability to reference NAS via friendly name)
      apt:
        name: avahi-daemon
        state: present

    # Mount the NAS
    - name: Mount NAS using 
      lineinfile:
        dest: /etc/fstab
        state: present
        line: '//{{ nas_name }}.local/Public {{ nas_mount_location }} cifs rw,guest,uid=1000,iocharset=utf8 0 0'

    # Set up required plex
    - name: make plex directory
      file:
        path: '{{ plex_directory }}'
        state: directory
        mode: 0755
        owner: root
        group: root
    - name: create environment variable file
      file:
        path: "{{ environment_file_location }}"
        state: touch
    - name: put plex claim in environment variable
      lineinfile:
        dest: "{{ environment_file_location }}"
        state: present
        line: 'PLEX_CLAIM={{ plex_claim }}'
    - name: put mount location in environment variable
      lineinfile:
        dest: "{{ environment_file_location }}"
        state: present
        line: 'PLEX_MNT_LOCATION={{ nas_mount_location }}'
    - name: put plex directory location in environment variable
      lineinfile:
        dest: "{{ environment_file_location }}"
        state: present
        line: 'PLEX_DIRECTORY={{ plex_directory }}'
    - name: put docker compose file location in environment variable for use with plex_server startup script
      lineinfile:
        dest: "{{ environment_file_location }}"
        state: present
        line: 'PLEX_DOCKER_COMPOSE_LOC={{ docker_compose_file_location_local }}'
    - name: copy startup script file to local/bin
      copy:
        src: "{{ plex_startup_script_local_location }}"
        dest: "{{ plex_startup_script_bin_location }}"
        owner: root
        group: root
        mode: 0555
    - name: copy systemd script to systemd location
      copy:
        src: "{{ systemd_file_location_local }}"
        dest: "{{ systemd_file_location }}"
        owner: root
        group: root
        mode: 0555

    # Set up sonarr
    - name: make sonarr directory
      file:
        path: '{{ sonarr_directory }}'
        state: directory
        mode: 666
        owner: root
        group: root
    - name: put sonarr directory location in environment variable
      lineinfile:
        dest: "{{ environment_file_location }}"
        state: present
        line: 'SONARR_DIRECTORY={{ sonarr_directory }}'

    # Set up sabnzbd
    - name: make sabnzdb group
      group:
        name: sabnzbd
        state: present
        gid: 666
    - name: make sabnzdb user
      user:
        name: sabnzbd
        state: present
        uid: 666
        group: 666
    - name: make sab directory
      file:
        path: '{{ sabnzbd_directory }}'
        state: directory
        owner: 666
        group: 666
        mode: 0755
    - name: put sab directory location in environment variable
      lineinfile:
        dest: "{{ environment_file_location }}"
        state: present
        line: 'SABNZBD_DIRECTORY={{ sabnzbd_directory }}'