---
- hosts: seedbox
  vars:
    transmission_location: /srv/transmission
    transmission_shared_download_dir: /mnt/seedbox/downloads

    docker_compose_file_name: "docker-compose.yml"
    docker_compose_file_location_local: "{{ playbook_dir }}/../docker/SEEDBOX"
    docker_compose_file_location_remote: "/srv/seedbox"

    # The below environment file location is hardcoded in the systemd script
    environment_file_location: "/etc/environment"

    startup_script: seedbox
    startup_script_local_location: "{{ playbook_dir }}/../systemd/{{ startup_script }}"
    # the below location is hardcoded in the systemd script
    startup_script_remote_location: "/usr/local/bin/{{ startup_script }}"

    systemd_file_location_local: "{{ playbook_dir }}/../systemd/qbittorent-nox.service"
    systemd_file_location_remote: "/etc/systemd/qbittorent-nox.service"

    transmission_settings_local: "{{ playbook_dir }}/../transmission/settings.json.j2"
    transmission_settings_remote: "/var/lib/transmission-daemon/.config/transmission-daemon/settings.json"
  
  tasks:
    - name: include secrets file
      include_vars: secrets.yml
   
    - name: install transmission clie
      apt:
        name: transmission-cli
        state: present
    - name: install transmission common
      apt:
        name: transmission-common
        state: present
    - name: install transmission daemon
      apt:
        name: transmission-daemon
        state: present
    - name: install qbittorent
      apt:
        name: qbittorrent
        state: present

    # set up required things for qbittorent
    - name: Make sure we have a 'wheel' group
      group:
        name: wheel
        state: present
    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: "%wheel ALL=(ALL) NOPASSWD: ALL"
    - name: add user qbtuser
      user:
        name: qbtuser
        groups: wheel
        state: present
    - name: copy systemd script to systemd location
      copy:
        src: "{{ systemd_file_location_local }}"
        dest: "{{ systemd_file_location_remote }}"
        owner: root
        group: root
        mode: 0555

    # Set up required things for transmission
    - name: make transmission directory
      file:
        path: '{{ transmission_location }}'
        state: directory
        mode: 0755
        owner: root
        group: root
    - name: make docker directory (to hold init file)
      file:
        path: '{{ docker_compose_file_location_remote }}'
        state: directory
        mode: 0755
        owner: root
        group: root
    - name: make transmission download directory
      file:
        path: '{{ transmission_shared_download_dir }}'
        state: directory
        mode: 0775
        owner: debian-transmission
        group: debian-transmission

    - name: stop transmission daemon
      service:
        name: transmission-daemon
        state: stopped
    ### Setup transmission settings
    - name: copy transmission settings file
      template:
        src: "{{ transmission_settings_local }}"
        dest: "{{ transmission_settings_remote }}"
      vars:
        transmission_password: "{{ transmission_password }}"
        transmission_download_dir: "{{ transmission_shared_download_dir }}"
#      copy:
#        src: "{{ transmission_settings_local }}"
#        dest: "{{ transmission_settings_remote }}"
#        owner: root
#        group: root
#        mode: 0555
    - name: start transmission daemon
      service:
        name: transmission-daemon
        state: started

    ### Setup env variables
    - name: create environment variable file
      file:
        path: "{{ environment_file_location }}"
        state: touch
    - name: put docker compose file location in environment variable for use with seedbox startup script
      lineinfile:
        dest: "{{ environment_file_location }}"
        state: present
        line: 'DOCKER_COMPOSE_LOC={{ docker_compose_file_location_remote }}/{{ docker_compose_file_name }}'
    - name: put transmission directory for use with docker-compose
      lineinfile:
        dest: "{{ environment_file_location }}"
        state: present
        line: 'TRANSMISSION_LOC={{ transmission_location }}'
